name: Push Notification to API

on:
  push:
    branches:
      - main  # Altere para a branch desejada

jobs:
  notify-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script Python
        run: python .github/workflows/send_push.py
